[package]
name = "mtaptos"
version = "1.0.0"
authors = ['Nick Culpin - https://github.com/njculpin']

[addresses]
weather_addr='580adc1efb1099fa4638517bbe51f43c90bfd50b6c747329c904c02e7c3aa678'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]


